name: CI (Java Gradle)

on:
  workflow_call:
    inputs:
      java-version:
        type: number
        required: true
      distribution:
        type: string
        required: false
        default: "temurin"
      command:
        type: string
        required: false
        default: "./gradlew build"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ${{ inputs.command }}
