name: CI (Node.js)

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        required: false
        default: 16
      setup-redis:
        type: boolean
        required: false
        default: false

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Setup Redis
        if: ${{ inputs.setup-redis }}
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test --if-present

      - name: Build
        run: npm run build --if-present -- --noEmit

      - name: Lint
        run: npm run lint --if-present -- --max-warnings=0
