name: Release (Mod)

on:
  workflow_call:
    inputs:
      java-version:
        type: number
        required: true
      distribution:
        type: string
        required: false
        default: "temurin"
      command:
        type: string
        required: false
        default: "./gradlew build"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ${{ inputs.command }}

      - name: Get Metadata
        id: metadata
        run: |
          echo "::set-output name=version::$(./gradlew properties -q | grep "modVersion" | awk '{print $2}')"
          echo "::set-output name=name::$(./gradlew properties -q | grep "modBaseName" | awk '{print $2}')"
          echo "::set-output name=mcVersion::$(./gradlew properties -q | grep "mcVersion" | awk '{print $2}')"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "[${{ steps.metadata.outputs.mcVersion }}] ${{ steps.metadata.outputs.name }} v${{ steps.metadata.outputs.version }}"
          tag_name: v${{ steps.metadata.outputs.version }}-${{ steps.metadata.outputs.mcVersion }}
          files: |
            build/libs/**/*.jar
